[package]
name = "crates-tui"
version = "0.1.0"
edition = "2021"
description = "A TUI for crates.io"
repository = "https://github.com/ratatui-org/crates-tui"
authors = ["The Ratatui Developers"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# FIXME - this seems pretty massive for a tutorial, which suggests that there may be some missing
# simplifications in the code.

better-panic = "0.3.0"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive", "cargo", "wrap_help", "unicode", "string", "unstable-styles", "color"] }
color-eyre = "0.6.2"
crates_io_api = "0.9.0"
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
derive_deref = "1.1.1"
directories = "5.0.1"
figment = { version = "0.10.14", features = ["env", "toml"] }
futures = "0.3.28"
human-panic = "1.2.0"
itertools = "0.12.0"
json5 = "0.4.1"
lazy_static = "1.4.0"
libc = "0.2.148"
num-format = "0.4.4"
pretty_assertions = "1.4.0"
ratatui = { version = "0.26.0", features = ["serde", "macros"] }
ratatui-macros = "0.2.3"
serde = { version = "1.0.188", features = ["derive"] }
serde_with = "3.5.0"
signal-hook = "0.3.17"
strip-ansi-escapes = "0.2.0"
strum = { version = "0.26.1", features = ["derive"] }
textwrap = "0.16.0"
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
toml = "0.8.8"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-error = "0.2.0"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "serde", "serde_json"] }
tui-input = "0.8.0"
unicode-width = "0.1.11"
uuid = "1.7.0"


[build-dependencies]
vergen = { version = "8.2.6", features = [ "build", "git", "gitoxide", "cargo" ]}
